/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Direction = { 'buy' : null } |
  { 'sell' : null };
export type Sensitivity = { 'conservative' : null } |
  { 'aggressive' : null } |
  { 'normal' : null };
export interface Settings {
  'signalSensitivity' : Sensitivity,
  'selectedTimeframe' : Timeframe,
}
export interface Signal {
  'id' : bigint,
  'rsi' : number,
  'direction' : Direction,
  'timeframe' : Timeframe,
  'ema9' : number,
  'ema21' : number,
  'confidenceScore' : bigint,
  'timestamp' : bigint,
  'candlePattern' : string,
  'outcome' : [] | [SignalOutcome],
}
export type SignalOutcome = { 'win' : null } |
  { 'loss' : null };
export type Timeframe = { 'd1' : null } |
  { 'h1' : null } |
  { 'm1' : null } |
  { 'm5' : null } |
  { 'w1' : null } |
  { 'm15' : null };
export interface _SERVICE {
  'getAllSignals' : ActorMethod<[], Array<Signal>>,
  'getLastSignals' : ActorMethod<[bigint], Array<Signal>>,
  'getSettings' : ActorMethod<[], [] | [Settings]>,
  'getSignalById' : ActorMethod<[bigint], [] | [Signal]>,
  'getSignalsByTimeframe' : ActorMethod<[Timeframe], Array<Signal>>,
  'saveSignal' : ActorMethod<
    [Direction, Timeframe, bigint, number, number, number, string],
    undefined
  >,
  'saveSignalOutcome' : ActorMethod<[bigint, SignalOutcome], undefined>,
  'updateSettings' : ActorMethod<[Timeframe, Sensitivity], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];