/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Direction = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const Timeframe = IDL.Variant({
  'd1' : IDL.Null,
  'h1' : IDL.Null,
  'm1' : IDL.Null,
  'm5' : IDL.Null,
  'w1' : IDL.Null,
  'm15' : IDL.Null,
});
export const SignalOutcome = IDL.Variant({
  'win' : IDL.Null,
  'loss' : IDL.Null,
});
export const Signal = IDL.Record({
  'id' : IDL.Nat,
  'rsi' : IDL.Float64,
  'direction' : Direction,
  'timeframe' : Timeframe,
  'ema9' : IDL.Float64,
  'ema21' : IDL.Float64,
  'confidenceScore' : IDL.Nat,
  'timestamp' : IDL.Int,
  'candlePattern' : IDL.Text,
  'outcome' : IDL.Opt(SignalOutcome),
});
export const Sensitivity = IDL.Variant({
  'conservative' : IDL.Null,
  'aggressive' : IDL.Null,
  'normal' : IDL.Null,
});
export const Settings = IDL.Record({
  'signalSensitivity' : Sensitivity,
  'selectedTimeframe' : Timeframe,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'getAllSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
  'getLastSignals' : IDL.Func([IDL.Nat], [IDL.Vec(Signal)], ['query']),
  'getSettings' : IDL.Func([], [IDL.Opt(Settings)], ['query']),
  'getSignalById' : IDL.Func([IDL.Nat], [IDL.Opt(Signal)], ['query']),
  'getSignalsByTimeframe' : IDL.Func([Timeframe], [IDL.Vec(Signal)], ['query']),
  'hasUser' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'loginUser' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'saveSignal' : IDL.Func(
      [
        Direction,
        Timeframe,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [],
      [],
    ),
  'saveSignalOutcome' : IDL.Func([IDL.Nat, SignalOutcome], [], []),
  'updateSettings' : IDL.Func([Timeframe, Sensitivity], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Direction = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const Timeframe = IDL.Variant({
    'd1' : IDL.Null,
    'h1' : IDL.Null,
    'm1' : IDL.Null,
    'm5' : IDL.Null,
    'w1' : IDL.Null,
    'm15' : IDL.Null,
  });
  const SignalOutcome = IDL.Variant({ 'win' : IDL.Null, 'loss' : IDL.Null });
  const Signal = IDL.Record({
    'id' : IDL.Nat,
    'rsi' : IDL.Float64,
    'direction' : Direction,
    'timeframe' : Timeframe,
    'ema9' : IDL.Float64,
    'ema21' : IDL.Float64,
    'confidenceScore' : IDL.Nat,
    'timestamp' : IDL.Int,
    'candlePattern' : IDL.Text,
    'outcome' : IDL.Opt(SignalOutcome),
  });
  const Sensitivity = IDL.Variant({
    'conservative' : IDL.Null,
    'aggressive' : IDL.Null,
    'normal' : IDL.Null,
  });
  const Settings = IDL.Record({
    'signalSensitivity' : Sensitivity,
    'selectedTimeframe' : Timeframe,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  
  return IDL.Service({
    'getAllSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
    'getLastSignals' : IDL.Func([IDL.Nat], [IDL.Vec(Signal)], ['query']),
    'getSettings' : IDL.Func([], [IDL.Opt(Settings)], ['query']),
    'getSignalById' : IDL.Func([IDL.Nat], [IDL.Opt(Signal)], ['query']),
    'getSignalsByTimeframe' : IDL.Func(
        [Timeframe],
        [IDL.Vec(Signal)],
        ['query'],
      ),
    'hasUser' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'loginUser' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'saveSignal' : IDL.Func(
        [
          Direction,
          Timeframe,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [],
        [],
      ),
    'saveSignalOutcome' : IDL.Func([IDL.Nat, SignalOutcome], [], []),
    'updateSettings' : IDL.Func([Timeframe, Sensitivity], [], []),
  });
};

export const init = ({ IDL }) => { return []; };