/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Signal {
    id: bigint;
    rsi: number;
    direction: Direction;
    timeframe: Timeframe;
    ema9: number;
    ema21: number;
    confidenceScore: bigint;
    timestamp: bigint;
    candlePattern: string;
    outcome?: SignalOutcome;
}
export interface Settings {
    signalSensitivity: Sensitivity;
    selectedTimeframe: Timeframe;
}
export enum Direction {
    buy = "buy",
    sell = "sell"
}
export enum Sensitivity {
    conservative = "conservative",
    aggressive = "aggressive",
    normal = "normal"
}
export enum SignalOutcome {
    win = "win",
    loss = "loss"
}
export enum Timeframe {
    d1 = "d1",
    h1 = "h1",
    m1 = "m1",
    m5 = "m5",
    w1 = "w1",
    m15 = "m15"
}
export interface backendInterface {
    getAllSignals(): Promise<Array<Signal>>;
    getLastSignals(limit: bigint): Promise<Array<Signal>>;
    getSettings(): Promise<Settings | null>;
    getSignalById(signalId: bigint): Promise<Signal | null>;
    getSignalsByTimeframe(timeframe: Timeframe): Promise<Array<Signal>>;
    saveSignal(direction: Direction, timeframe: Timeframe, confidenceScore: bigint, ema9: number, ema21: number, rsi: number, candlePattern: string): Promise<void>;
    saveSignalOutcome(signalId: bigint, outcome: SignalOutcome): Promise<void>;
    updateSettings(selectedTimeframe: Timeframe, signalSensitivity: Sensitivity): Promise<void>;
}
import type { Direction as _Direction, Sensitivity as _Sensitivity, Settings as _Settings, Signal as _Signal, SignalOutcome as _SignalOutcome, Timeframe as _Timeframe } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllSignals(): Promise<Array<Signal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSignals();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSignals();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLastSignals(arg0: bigint): Promise<Array<Signal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastSignals(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastSignals(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<Settings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSignalById(arg0: bigint): Promise<Signal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSignalById(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSignalById(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSignalsByTimeframe(arg0: Timeframe): Promise<Array<Signal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSignalsByTimeframe(to_candid_Timeframe_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSignalsByTimeframe(to_candid_Timeframe_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveSignal(arg0: Direction, arg1: Timeframe, arg2: bigint, arg3: number, arg4: number, arg5: number, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSignal(to_candid_Direction_n19(this._uploadFile, this._downloadFile, arg0), to_candid_Timeframe_n17(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSignal(to_candid_Direction_n19(this._uploadFile, this._downloadFile, arg0), to_candid_Timeframe_n17(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async saveSignalOutcome(arg0: bigint, arg1: SignalOutcome): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSignalOutcome(arg0, to_candid_SignalOutcome_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSignalOutcome(arg0, to_candid_SignalOutcome_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSettings(arg0: Timeframe, arg1: Sensitivity): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(to_candid_Timeframe_n17(this._uploadFile, this._downloadFile, arg0), to_candid_Sensitivity_n23(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(to_candid_Timeframe_n17(this._uploadFile, this._downloadFile, arg0), to_candid_Sensitivity_n23(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Direction_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Direction): Direction {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Sensitivity_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sensitivity): Sensitivity {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Settings_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Settings): Settings {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_SignalOutcome_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignalOutcome): SignalOutcome {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Signal_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Signal): Signal {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Timeframe_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Timeframe): Timeframe {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Settings]): Settings | null {
    return value.length === 0 ? null : from_candid_Settings_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Signal]): Signal | null {
    return value.length === 0 ? null : from_candid_Signal_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SignalOutcome]): SignalOutcome | null {
    return value.length === 0 ? null : from_candid_SignalOutcome_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    signalSensitivity: _Sensitivity;
    selectedTimeframe: _Timeframe;
}): {
    signalSensitivity: Sensitivity;
    selectedTimeframe: Timeframe;
} {
    return {
        signalSensitivity: from_candid_Sensitivity_n14(_uploadFile, _downloadFile, value.signalSensitivity),
        selectedTimeframe: from_candid_Timeframe_n6(_uploadFile, _downloadFile, value.selectedTimeframe)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    rsi: number;
    direction: _Direction;
    timeframe: _Timeframe;
    ema9: number;
    ema21: number;
    confidenceScore: bigint;
    timestamp: bigint;
    candlePattern: string;
    outcome: [] | [_SignalOutcome];
}): {
    id: bigint;
    rsi: number;
    direction: Direction;
    timeframe: Timeframe;
    ema9: number;
    ema21: number;
    confidenceScore: bigint;
    timestamp: bigint;
    candlePattern: string;
    outcome?: SignalOutcome;
} {
    return {
        id: value.id,
        rsi: value.rsi,
        direction: from_candid_Direction_n4(_uploadFile, _downloadFile, value.direction),
        timeframe: from_candid_Timeframe_n6(_uploadFile, _downloadFile, value.timeframe),
        ema9: value.ema9,
        ema21: value.ema21,
        confidenceScore: value.confidenceScore,
        timestamp: value.timestamp,
        candlePattern: value.candlePattern,
        outcome: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.outcome))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    win: null;
} | {
    loss: null;
}): SignalOutcome {
    return "win" in value ? SignalOutcome.win : "loss" in value ? SignalOutcome.loss : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    conservative: null;
} | {
    aggressive: null;
} | {
    normal: null;
}): Sensitivity {
    return "conservative" in value ? Sensitivity.conservative : "aggressive" in value ? Sensitivity.aggressive : "normal" in value ? Sensitivity.normal : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): Direction {
    return "buy" in value ? Direction.buy : "sell" in value ? Direction.sell : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    d1: null;
} | {
    h1: null;
} | {
    m1: null;
} | {
    m5: null;
} | {
    w1: null;
} | {
    m15: null;
}): Timeframe {
    return "d1" in value ? Timeframe.d1 : "h1" in value ? Timeframe.h1 : "m1" in value ? Timeframe.m1 : "m5" in value ? Timeframe.m5 : "w1" in value ? Timeframe.w1 : "m15" in value ? Timeframe.m15 : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Signal>): Array<Signal> {
    return value.map((x)=>from_candid_Signal_n2(_uploadFile, _downloadFile, x));
}
function to_candid_Direction_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Direction): _Direction {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_Sensitivity_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sensitivity): _Sensitivity {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_SignalOutcome_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalOutcome): _SignalOutcome {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_Timeframe_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timeframe): _Timeframe {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timeframe): {
    d1: null;
} | {
    h1: null;
} | {
    m1: null;
} | {
    m5: null;
} | {
    w1: null;
} | {
    m15: null;
} {
    return value == Timeframe.d1 ? {
        d1: null
    } : value == Timeframe.h1 ? {
        h1: null
    } : value == Timeframe.m1 ? {
        m1: null
    } : value == Timeframe.m5 ? {
        m5: null
    } : value == Timeframe.w1 ? {
        w1: null
    } : value == Timeframe.m15 ? {
        m15: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Direction): {
    buy: null;
} | {
    sell: null;
} {
    return value == Direction.buy ? {
        buy: null
    } : value == Direction.sell ? {
        sell: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalOutcome): {
    win: null;
} | {
    loss: null;
} {
    return value == SignalOutcome.win ? {
        win: null
    } : value == SignalOutcome.loss ? {
        loss: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sensitivity): {
    conservative: null;
} | {
    aggressive: null;
} | {
    normal: null;
} {
    return value == Sensitivity.conservative ? {
        conservative: null
    } : value == Sensitivity.aggressive ? {
        aggressive: null
    } : value == Sensitivity.normal ? {
        normal: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
